server:
  port: 8089
  servlet:
    context-path: /api

management:
  security:
    enabled: false

spring:
  application:
    name: gtd-es-command-side
  kafka:
    bootstrapServers: localhost:9092
    consumer:
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: net.mguenther.gtd.kafka.serialization.StockEventDeserializer
      autoOffsetReset: earliest
      enableAutoCommit: false
      isolationLevel: READ_COMMITTED
    listener:
      ackMode: MANUAL
    producer:
      bootstrapServers: localhost:9092
      transaction-id-prefix: gtd-es

gtd:
  topic: topic-getting-things-done
  groupId: getting-thigns-done-command

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
  instance:
    appname: gtd-es-command-side
    preferIpAddress: true
