/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.gtd.kafka.serialization;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroStockCreated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1102172486391950787L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroStockCreated\",\"namespace\":\"net.mguenther.gtd.kafka.serialization\",\"fields\":[{\"name\":\"comapnyCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"stockPrice\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String comapnyCode;
  @Deprecated public java.lang.String stockPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroStockCreated() {}

  /**
   * All-args constructor.
   * @param comapnyCode The new value for comapnyCode
   * @param stockPrice The new value for stockPrice
   */
  public AvroStockCreated(java.lang.String comapnyCode, java.lang.String stockPrice) {
    this.comapnyCode = comapnyCode;
    this.stockPrice = stockPrice;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return comapnyCode;
    case 1: return stockPrice;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: comapnyCode = (java.lang.String)value$; break;
    case 1: stockPrice = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'comapnyCode' field.
   * @return The value of the 'comapnyCode' field.
   */
  public java.lang.String getComapnyCode() {
    return comapnyCode;
  }

  /**
   * Sets the value of the 'comapnyCode' field.
   * @param value the value to set.
   */
  public void setComapnyCode(java.lang.String value) {
    this.comapnyCode = value;
  }

  /**
   * Gets the value of the 'stockPrice' field.
   * @return The value of the 'stockPrice' field.
   */
  public java.lang.String getStockPrice() {
    return stockPrice;
  }

  /**
   * Sets the value of the 'stockPrice' field.
   * @param value the value to set.
   */
  public void setStockPrice(java.lang.String value) {
    this.stockPrice = value;
  }

  /**
   * Creates a new AvroStockCreated RecordBuilder.
   * @return A new AvroStockCreated RecordBuilder
   */
  public static net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder newBuilder() {
    return new net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder();
  }

  /**
   * Creates a new AvroStockCreated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroStockCreated RecordBuilder
   */
  public static net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder newBuilder(net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder other) {
    return new net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder(other);
  }

  /**
   * Creates a new AvroStockCreated RecordBuilder by copying an existing AvroStockCreated instance.
   * @param other The existing instance to copy.
   * @return A new AvroStockCreated RecordBuilder
   */
  public static net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder newBuilder(net.mguenther.gtd.kafka.serialization.AvroStockCreated other) {
    return new net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder(other);
  }

  /**
   * RecordBuilder for AvroStockCreated instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroStockCreated>
    implements org.apache.avro.data.RecordBuilder<AvroStockCreated> {

    private java.lang.String comapnyCode;
    private java.lang.String stockPrice;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.comapnyCode)) {
        this.comapnyCode = data().deepCopy(fields()[0].schema(), other.comapnyCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stockPrice)) {
        this.stockPrice = data().deepCopy(fields()[1].schema(), other.stockPrice);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroStockCreated instance
     * @param other The existing instance to copy.
     */
    private Builder(net.mguenther.gtd.kafka.serialization.AvroStockCreated other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.comapnyCode)) {
        this.comapnyCode = data().deepCopy(fields()[0].schema(), other.comapnyCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stockPrice)) {
        this.stockPrice = data().deepCopy(fields()[1].schema(), other.stockPrice);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'comapnyCode' field.
      * @return The value.
      */
    public java.lang.String getComapnyCode() {
      return comapnyCode;
    }

    /**
      * Sets the value of the 'comapnyCode' field.
      * @param value The value of 'comapnyCode'.
      * @return This builder.
      */
    public net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder setComapnyCode(java.lang.String value) {
      validate(fields()[0], value);
      this.comapnyCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'comapnyCode' field has been set.
      * @return True if the 'comapnyCode' field has been set, false otherwise.
      */
    public boolean hasComapnyCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'comapnyCode' field.
      * @return This builder.
      */
    public net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder clearComapnyCode() {
      comapnyCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'stockPrice' field.
      * @return The value.
      */
    public java.lang.String getStockPrice() {
      return stockPrice;
    }

    /**
      * Sets the value of the 'stockPrice' field.
      * @param value The value of 'stockPrice'.
      * @return This builder.
      */
    public net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder setStockPrice(java.lang.String value) {
      validate(fields()[1], value);
      this.stockPrice = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'stockPrice' field has been set.
      * @return True if the 'stockPrice' field has been set, false otherwise.
      */
    public boolean hasStockPrice() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'stockPrice' field.
      * @return This builder.
      */
    public net.mguenther.gtd.kafka.serialization.AvroStockCreated.Builder clearStockPrice() {
      stockPrice = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroStockCreated build() {
      try {
        AvroStockCreated record = new AvroStockCreated();
        record.comapnyCode = fieldSetFlags()[0] ? this.comapnyCode : (java.lang.String) defaultValue(fields()[0]);
        record.stockPrice = fieldSetFlags()[1] ? this.stockPrice : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
